/* ------------------------------------------------------------------
   DATA
   Keys are "month-day" (1-indexed month, no zero padding).
   Everything here is bundled — no network calls, no API keys.
------------------------------------------------------------------- */

export const DAILY = {
  "1-1": ["New Year's Day", "Polar Bear Plunge Day", "National Hangover Day", "Copyright Law Day", "Z Day"],
  "1-2": ["National Science Fiction Day", "Run It Up the Flagpole and See if Anyone Salutes It Day", "National Buffet Day", "Happy Mew Year for Cats Day"],
  "1-3": ["Festival of Sleep Day", "Fruitcake Toss Day", "Humiliation Day", "National Chocolate Covered Cherry Day", "Drinking Straw Day"],
  "1-4": ["Trivia Day", "National Spaghetti Day", "World Braille Day", "Dimpled Chad Day"],
  "1-5": ["National Bird Day", "National Whipped Cream Day", "Twelfth Night"],
  "1-6": ["Bean Day", "Cuddle Up Day", "Epiphany", "National Shortbread Day"],
  "1-7": ["Old Rock Day", "I'm Not Going to Take It Anymore Day", "National Tempura Day", "Orthodox Christmas"],
  "1-8": ["Bubble Bath Day", "Earth's Rotation Day", "National English Toffee Day", "Elvis Presley Day"],
  "1-9": ["Play God Day", "National Apricot Day", "Balloon Ascension Day", "Static Electricity Day"],
  "1-10": ["Peculiar People Day", "Houseplant Appreciation Day", "National Bittersweet Chocolate Day", "Save the Eagles Day"],
  "1-11": ["Step in a Puddle and Splash Your Friend's Day", "National Milk Day", "Learn Your Name in Morse Code Day"],
  "1-12": ["Feast of Fabulous Wild Men Day", "National Pharmacist Day", "National Curried Chicken Day"],
  "1-13": ["International Skeptics Day", "Make Your Dream Come True Day", "National Rubber Ducky Day", "National Peach Melba Day"],
  "1-14": ["Dress Up Your Pet Day", "National Hot Pastrami Sandwich Day", "Ratification Day"],
  "1-15": ["National Hat Day", "National Bagel Day", "Humanitarian Day"],
  "1-16": ["National Nothing Day", "Appreciate a Dragon Day", "National Fig Newton Day", "Hot and Spicy Food International Day"],
  "1-17": ["Ditch New Year's Resolutions Day", "Judgment Day", "Kid Inventors' Day", "National Hot Buttered Rum Day"],
  "1-18": ["Thesaurus Day", "Winnie the Pooh Day", "National Peking Duck Day"],
  "1-19": ["National Popcorn Day", "National Tin Can Day", "Brew a Potion Day"],
  "1-20": ["National Buttercrunch Day", "Penguin Awareness Day", "National Cheese Lover's Day", "Camcorder Day"],
  "1-21": ["National Hugging Day", "Squirrel Appreciation Day", "National Granola Bar Day", "International Sweatpants Day"],
  "1-22": ["National Blonde Brownie Day", "Answer Your Cat's Questions Day", "Celebration of Life Day"],
  "1-23": ["National Handwriting Day", "Measure Your Feet Day", "National Pie Day", "Snowplow Mailbox Hockey Day"],
  "1-24": ["Beer Can Appreciation Day", "Compliment Day", "National Peanut Butter Day", "Talk Like a Grizzled Prospector Day"],
  "1-25": ["Opposite Day", "A Room of One's Own Day", "National Irish Coffee Day", "Burns Night"],
  "1-26": ["Spouse's Day", "Australia Day", "National Peanut Brittle Day", "Toad Hollow Day of Encouragement"],
  "1-27": ["Chocolate Cake Day", "Punch the Clock Day", "Thomas Crapper Day"],
  "1-28": ["National Kazoo Day", "Fun at Work Day", "National Blueberry Pancake Day", "Data Privacy Day"],
  "1-29": ["National Cornchip Day", "National Puzzle Day", "Freethinkers Day", "Curmudgeons Day"],
  "1-30": ["Escape Day", "National Croissant Day", "Yodel for Your Neighbors Day"],
  "1-31": ["Backward Day", "Inspire Your Heart with Art Day", "National Hot Chocolate Day", "Brandy Alexander Day"],

  "2-1": ["National Freedom Day", "Robinson Crusoe Day", "Decorating with Candy Day", "National Baked Alaska Day"],
  "2-2": ["Groundhog Day", "Candlemas", "Hedgehog Day", "National Tater Tot Day", "Crepe Day"],
  "2-3": ["Feed the Birds Day", "The Day the Music Died", "National Carrot Cake Day", "Elmo's Birthday"],
  "2-4": ["Create a Vacuum Day", "Thank a Mailman Day", "National Homemade Soup Day", "World Cancer Day"],
  "2-5": ["National Weatherperson's Day", "Disaster Day", "National Chocolate Fondue Day", "World Nutella Day"],
  "2-6": ["Lame Duck Day", "Pay a Compliment Day", "National Frozen Yogurt Day", "National Chopsticks Day"],
  "2-7": ["Wave All Your Fingers at Your Neighbors Day", "Send a Card to a Friend Day", "National Fettuccine Alfredo Day", "Ballet Day"],
  "2-8": ["Kite Flying Day", "Laugh and Get Rich Day", "Boy Scouts Day", "Molasses Bar Day"],
  "2-9": ["Toothache Day", "Read in the Bathtub Day", "National Bagels and Lox Day", "National Pizza Day"],
  "2-10": ["Umbrella Day", "Plimsoll Day", "National Cream Cheese Brownie Day"],
  "2-11": ["Don't Cry Over Spilled Milk Day", "Make a Friend Day", "White T-Shirt Day", "National Peppermint Patty Day"],
  "2-12": ["Lincoln's Birthday", "Darwin Day", "National Plum Pudding Day", "Extraterrestrial Culture Day"],
  "2-13": ["Get a Different Name Day", "Employee Legal Awareness Day", "National Tortellini Day", "World Radio Day"],
  "2-14": ["Valentine's Day", "Ferris Wheel Day", "National Cream-Filled Chocolates Day", "Library Lovers Day"],
  "2-15": ["National Gum Drop Day", "Susan B. Anthony Day", "Singles Awareness Day", "Annoy Squidward Day"],
  "2-16": ["Do a Grouch a Favor Day", "Innovation Day", "National Almond Day"],
  "2-17": ["Random Acts of Kindness Day", "Champion Crab Races Day", "My Way Day", "National Cabbage Day"],
  "2-18": ["National Battery Day", "Cow Milked While Flying in an Airplane Day", "National Drink Wine Day", "Pluto Day"],
  "2-19": ["National Chocolate Mint Day", "International Tug-of-War Day", "Iwo Jima Day"],
  "2-20": ["Cherry Pie Day", "Hoodie-Hoo Day", "Love Your Pet Day"],
  "2-21": ["Card Reading Day", "International Mother Language Day", "National Sticky Bun Day"],
  "2-22": ["Be Humble Day", "Walking the Dog Day", "National Margarita Day", "World Thinking Day"],
  "2-23": ["International Dog Biscuit Appreciation Day", "Curling is Cool Day", "National Banana Bread Day", "Tennis Day"],
  "2-24": ["National Tortilla Chip Day", "Inconvenience Yourself Day", "World Bartender Day"],
  "2-25": ["Pistol Patent Day", "Quiet Day", "National Clam Chowder Day"],
  "2-26": ["National Pistachio Day", "Carpe Diem Day", "Tell a Fairy Tale Day", "For Pete's Sake Day"],
  "2-27": ["No Brainer Day", "Polar Bear Day", "National Kahlua Day", "National Strawberry Day"],
  "2-28": ["Public Sleeping Day", "Floral Design Day", "National Chocolate Souffle Day", "Tooth Fairy Day"],
  "2-29": ["Leap Day", "Bachelor's Day", "Rare Disease Day"],

  "3-1": ["National Pig Day", "Peanut Butter Lover's Day", "Share a Smile Day", "World Compliment Day"],
  "3-2": ["Old Stuff Day", "Dr. Seuss Day", "National Banana Cream Pie Day", "Read Across America Day"],
  "3-3": ["I Want You to be Happy Day", "What if Cats and Dogs Had Opposable Thumbs Day", "National Cold Cuts Day", "World Wildlife Day"],
  "3-4": ["Holy Experiment Day", "Hug a G.I. Day", "National Pound Cake Day", "March Forth and Do Something Day"],
  "3-5": ["Multiple Personality Day", "National Cheese Doodle Day", "World Book Day"],
  "3-6": ["Dentist's Day", "Oreo Cookie Day", "National Frozen Food Day", "Namesake Day"],
  "3-7": ["National Crown Roast of Pork Day", "Cereal Day", "Be Heard Day"],
  "3-8": ["Be Nasty Day", "International Women's Day", "National Peanut Cluster Day", "Proofreading Day"],
  "3-9": ["Panic Day", "Get Over It Day", "National Crabmeat Day", "Barbie Day"],
  "3-10": ["Middle Name Pride Day", "Mario Day", "National Blueberry Popover Day", "Land Line Telephone Day"],
  "3-11": ["Johnny Appleseed Day", "Worship of Tools Day", "National Oatmeal Nut Waffles Day"],
  "3-12": ["Plant a Flower Day", "Girl Scouts Day", "National Baked Scallops Day", "Alfred Hitchcock Day"],
  "3-13": ["Jewel Day", "Ear Muff Day", "National Coconut Torte Day", "Good Samaritan Day"],
  "3-14": ["Pi Day", "National Potato Chip Day", "Learn About Butterflies Day", "National Save a Spider Day"],
  "3-15": ["Everything You Do is Right Day", "Ides of March", "Dumbstruck Day", "National Pears Helene Day"],
  "3-16": ["Everything You Do is Wrong Day", "Freedom of Information Day", "Lips Appreciation Day", "National Artichoke Hearts Day"],
  "3-17": ["St. Patrick's Day", "Submarine Day", "National Corned Beef and Cabbage Day", "Campfire Day"],
  "3-18": ["Awkward Moments Day", "Supreme Sacrifice Day", "National Sloppy Joe Day", "Forgive Mom and Dad Day"],
  "3-19": ["Poultry Day", "National Chocolate Caramel Day", "Let's Laugh Day", "Swallows Return to San Juan Capistrano Day"],
  "3-20": ["Extraterrestrial Abductions Day", "Proposal Day", "National Ravioli Day", "International Day of Happiness"],
  "3-21": ["Fragrance Day", "Common Courtesy Day", "National California Strawberry Day", "World Poetry Day"],
  "3-22": ["International Goof-Off Day", "National Bavarian Crepes Day", "World Water Day"],
  "3-23": ["National Chip and Dip Day", "Near Miss Day", "World Meteorological Day", "Melba Toast Day"],
  "3-24": ["National Chocolate Covered Raisin Day", "World Tuberculosis Day", "Cheesesteak Day"],
  "3-25": ["Pecan Day", "Waffle Day", "Tolkien Reading Day", "Feast of the Annunciation"],
  "3-26": ["Make Up Your Own Holiday Day", "National Spinach Day", "Legal Assistants Day"],
  "3-27": ["National \u201cJoe\u201d Day", "Quirky Country Music Song Titles Day", "National Spanish Paella Day", "World Theatre Day"],
  "3-28": ["Something on a Stick Day", "Weed Appreciation Day", "National Black Forest Cake Day"],
  "3-29": ["Smoke and Mirrors Day", "National Lemon Chiffon Cake Day", "Vietnam Veterans Day"],
  "3-30": ["I am in Control Day", "Take a Walk in the Park Day", "National Turkey Neck Soup Day", "Pencil Day"],
  "3-31": ["Bunsen Burner Day", "National Clam on the Half Shell Day", "World Backup Day", "Crayon Day"],

  "4-1": ["April Fool's Day", "International Fun at Work Day", "National Sourdough Bread Day", "One Cent Day"],
  "4-2": ["National Peanut Butter and Jelly Day", "International Children's Book Day", "World Autism Awareness Day", "Reconciliation Day"],
  "4-3": ["Don't Go to Work Unless it's Fun Day", "Tweed Day", "National Chocolate Mousse Day", "Find a Rainbow Day"],
  "4-4": ["Tell a Lie Day", "Vitamin C Day", "School Librarian Day", "National Cordon Bleu Day"],
  "4-5": ["Go for Broke Day", "Read a Road Map Day", "National Caramel Day", "National Deep Dish Pizza Day"],
  "4-6": ["Plan Your Epitaph Day", "Sorry Charlie Day", "National Caramel Popcorn Day", "Tartan Day"],
  "4-7": ["No Housework Day", "World Health Day", "National Coffee Cake Day", "National Beer Day"],
  "4-8": ["All is Ours Day", "Draw a Picture of a Bird Day", "National Empanada Day", "Zoo Lovers Day"],
  "4-9": ["Name Yourself Day", "Winston Churchill Day", "National Chinese Almond Cookie Day", "Unicorn Day"],
  "4-10": ["Golfer's Day", "National Siblings Day", "Encourage a Young Writer Day", "National Cinnamon Crescent Day"],
  "4-11": ["Eight Track Tape Day", "National Cheese Fondue Day", "Barbershop Quartet Day", "National Pet Day"],
  "4-12": ["Big Wind Day", "Grilled Cheese Sandwich Day", "Walk on Your Wild Side Day", "Licorice Day"],
  "4-13": ["Blame Someone Else Day", "Scrabble Day", "National Peach Cobbler Day", "Thomas Jefferson's Birthday"],
  "4-14": ["International Moment of Laughter Day", "Look Up at the Sky Day", "National Pecan Day", "Dolphin Day"],
  "4-15": ["Rubber Eraser Day", "Tax Day", "McDonald's Day", "Titanic Remembrance Day"],
  "4-16": ["National Eggs Benedict Day", "National Stress Awareness Day", "Wear Your Pajamas to Work Day", "Save the Elephant Day"],
  "4-17": ["Blah Blah Blah Day", "Bat Appreciation Day", "National Cheeseball Day", "Haiku Poetry Day"],
  "4-18": ["International Jugglers Day", "Newspaper Columnists Day", "National Animal Crackers Day", "Pet Owners Day"],
  "4-19": ["National Garlic Day", "Humorous Day", "Bicycle Day"],
  "4-20": ["National Pineapple Upside Down Cake Day", "Volunteer Recognition Day", "Look Alike Day"],
  "4-21": ["Kindergarten Day", "Bulldogs Are Beautiful Day", "National Chocolate Covered Cashews Day", "National Tea Day"],
  "4-22": ["Earth Day", "National Jelly Bean Day", "Girl Scout Leader Day"],
  "4-23": ["Lover's Day", "Talk Like Shakespeare Day", "National Cherry Cheesecake Day", "World Book Day"],
  "4-24": ["National Pigs in a Blanket Day", "National Bucket List Day", "Teach Your Daughter to Volunteer Day"],
  "4-25": ["East Meets West Day", "Hug a Plumber Day", "World Penguin Day", "National Zucchini Bread Day"],
  "4-26": ["Hug an Australian Day", "National Pretzel Day", "Richter Scale Day", "Audubon Day"],
  "4-27": ["Babe Ruth Day", "Tell a Story Day", "National Prime Rib Day", "Morse Code Day"],
  "4-28": ["Great Poetry Reading Day", "Kiss Your Mate Day", "National Blueberry Pie Day", "Superhero Day"],
  "4-29": ["International Dance Day", "Greenery Day", "National Shrimp Scampi Day", "Zipper Day"],
  "4-30": ["Hairstyle Appreciation Day", "National Honesty Day", "Bugs Bunny Day", "National Raisin Day"],

  "5-1": ["May Day", "Mother Goose Day", "Save the Rhino Day", "National Chocolate Parfait Day", "Lei Day"],
  "5-2": ["Baby Day", "Fire Day", "National Truffle Day", "Brothers and Sisters Day"],
  "5-3": ["Lumpy Rug Day", "Two Different Colored Shoes Day", "National Chocolate Custard Day", "Paranormal Day"],
  "5-4": ["Renewal Day", "Star Wars Day", "National Candied Orange Peel Day", "Bird Day"],
  "5-5": ["Cinco de Mayo", "National Hoagie Day", "Oyster Day", "Totally Chipotle Day"],
  "5-6": ["Beverage Day", "No Diet Day", "National Crepes Suzette Day", "National Nurses Day"],
  "5-7": ["National Roast Leg of Lamb Day", "Paste Up Day", "Cosmopolitan Day"],
  "5-8": ["No Socks Day", "Have a Coke Day", "National Coconut Cream Pie Day", "World Red Cross Day"],
  "5-9": ["Lost Sock Memorial Day", "National Butterscotch Brownie Day", "Sleepover Day"],
  "5-10": ["Clean up Your Room Day", "National Shrimp Day", "Stay Up All Night Night"],
  "5-11": ["Eat What You Want Day", "Twilight Zone Day", "National Foam Rolling Day"],
  "5-12": ["Limerick Day", "National Nutty Fudge Day", "Odometer Day", "Fatigue Syndrome Day"],
  "5-13": ["Frog Jumping Day", "Leprechaun Day", "National Apple Pie Day", "Top Gun Day"],
  "5-14": ["Dance Like a Chicken Day", "National Buttermilk Biscuit Day", "Underground America Day"],
  "5-15": ["National Chocolate Chip Day", "Straw Hat Day", "Nylon Stockings Day", "Peace Officers Memorial Day"],
  "5-16": ["Wear Purple for Peace Day", "Love a Tree Day", "National Barbecue Day", "Biographers Day"],
  "5-17": ["Pack Rat Day", "National Cherry Cobbler Day", "World Baking Day"],
  "5-18": ["International Museum Day", "No Dirty Dishes Day", "Visit Your Relatives Day", "National Cheese Souffle Day"],
  "5-19": ["Boy's Club Day", "National Devil's Food Cake Day", "World Plant a Vegetable Garden Day"],
  "5-20": ["Be a Millionaire Day", "Eliza Doolittle Day", "Pick Strawberries Day", "National Quiche Lorraine Day"],
  "5-21": ["National Memo Day", "National Strawberries and Cream Day", "Talk Like Yoda Day"],
  "5-22": ["Buy a Musical Instrument Day", "National Vanilla Pudding Day", "World Goth Day"],
  "5-23": ["Lucky Penny Day", "World Turtle Day", "National Taffy Day", "Title Track Day"],
  "5-24": ["Brother's Day", "National Escargot Day", "Scavenger Hunt Day"],
  "5-25": ["National Tap Dance Day", "National Wine Day", "Towel Day", "Geek Pride Day"],
  "5-26": ["Sally Ride Day", "National Blueberry Cheesecake Day", "National Paper Airplane Day"],
  "5-27": ["Cellophane Tape Day", "National Grape Popsicle Day", "Sun Screen Day"],
  "5-28": ["Amnesty International Day", "National Brisket Day", "Slugs Return from Capistrano Day"],
  "5-29": ["Learn About Composting Day", "End of the Middle Ages Day", "National Coq au Vin Day", "Put a Pillow on Your Fridge Day"],
  "5-30": ["Loomis Day", "My Bucket's Got a Hole in It Day", "National Mint Julep Day", "Water a Flower Day"],
  "5-31": ["Macaroon Day", "Save Your Hearing Day", "World No Tobacco Day", "Speak in Complete Sentences Day"],

  "6-1": ["Dare Day", "Say Something Nice Day", "National Hazelnut Cake Day", "Flip a Coin Day"],
  "6-2": ["National Bubba Day", "Yell \u201cFudge\u201d at the Cobras in North America Day", "National Rocky Road Day", "Rotisserie Chicken Day"],
  "6-3": ["Repeat Day", "Egg Day", "National Chocolate Macaroon Day", "World Bicycle Day"],
  "6-4": ["Applesauce Cake Day", "Old Maid's Day", "Hug Your Cat Day", "National Cheese Day"],
  "6-5": ["World Environment Day", "Hot Air Balloon Day", "National Gingerbread Day", "Festival of Popular Delusions Day"],
  "6-6": ["D-Day", "National Yo-Yo Day", "Drive-In Movie Day", "National Applesauce Cake Day"],
  "6-7": ["National Chocolate Ice Cream Day", "VCR Day", "Boone Day"],
  "6-8": ["Best Friends Day", "Name Your Poison Day", "Upsy Daisy Day", "World Oceans Day"],
  "6-9": ["Donald Duck Day", "National Strawberry Rhubarb Pie Day", "Coral Triangle Day"],
  "6-10": ["Ball Point Pen Day", "Iced Tea Day", "National Herbs and Spices Day"],
  "6-11": ["National Corn on the Cob Day", "King Kamehameha Day", "National German Chocolate Cake Day"],
  "6-12": ["Red Rose Day", "National Peanut Butter Cookie Day", "Loving Day", "Superman Day"],
  "6-13": ["Sewing Machine Day", "Kitchen Klutzes of America Day", "National Cucumber Day", "Weed Your Garden Day"],
  "6-14": ["Flag Day", "Pop Goes the Weasel Day", "National Strawberry Shortcake Day", "World Blood Donor Day"],
  "6-15": ["Smile Power Day", "Nature Photography Day", "National Lobster Day", "Global Wind Day"],
  "6-16": ["Fresh Veggies Day", "National Fudge Day", "Ladies Day"],
  "6-17": ["Eat Your Vegetables Day", "National Apple Strudel Day", "World Juggling Day", "Stewart's Root Beer Day"],
  "6-18": ["Go Fishing Day", "International Panic Day", "National Splurge Day", "International Sushi Day"],
  "6-19": ["Juneteenth", "World Sauntering Day", "National Martini Day", "Garfield the Cat Day"],
  "6-20": ["Ice Cream Soda Day", "American Eagle Day", "National Vanilla Milkshake Day", "World Refugee Day"],
  "6-21": ["Go Skateboarding Day", "National Daylight Appreciation Day", "World Giraffe Day", "National Peaches and Cream Day"],
  "6-22": ["National Chocolate Eclair Day", "Stupid Guy Thing Day", "World Rainforest Day"],
  "6-23": ["National Pink Day", "National Typewriter Day", "Let It Go Day", "National Hydration Day"],
  "6-24": ["Swim a Lap Day", "International Fairy Day", "National Pralines Day", "Celebration of the Senses"],
  "6-25": ["Log Cabin Day", "Global Beatles Day", "National Strawberry Parfait Day", "Color TV Day"],
  "6-26": ["Beautician's Day", "Forgiveness Day", "National Chocolate Pudding Day"],
  "6-27": ["Decide to be Married Day", "Sunglasses Day", "National Orange Blossom Day", "Helen Keller Day"],
  "6-28": ["Insurance Awareness Day", "Paul Bunyan Day", "Tau Day", "National Ceviche Day"],
  "6-29": ["Camera Day", "Waffle Iron Day", "Hug Holiday"],
  "6-30": ["Meteor Day", "Social Media Day", "Asteroid Day"],

  "7-1": ["Canada Day", "International Joke Day", "National Gingersnap Day", "Postal Worker Day"],
  "7-2": ["I Forgot Day", "World UFO Day", "National Anisette Day", "Made in the USA Day"],
  "7-3": ["Compliment Your Mirror Day", "Stay Out of the Sun Day", "National Eat Your Beans Day", "Disobedience Day"],
  "7-4": ["Independence Day", "National Country Music Day", "Sidewalk Egg Frying Day", "National Barbecued Spareribs Day"],
  "7-5": ["Bikini Day", "Work-a-holics Day", "National Apple Turnover Day", "Graham Cracker Day"],
  "7-6": ["National Fried Chicken Day", "International Kissing Day", "Take Your Webmaster to Lunch Day"],
  "7-7": ["Chocolate Day", "Father-Daughter Take a Walk Together Day", "National Strawberry Sundae Day", "Tell the Truth Day"],
  "7-8": ["Video Games Day", "Math 2.0 Day", "National Milk Chocolate with Almonds Day", "Body Painting Day"],
  "7-9": ["National Sugar Cookie Day", "Fashion Day", "Don't Put All Your Eggs in One Basket Day"],
  "7-10": ["Teddy Bear Picnic Day", "Clerihew Day", "National Pina Colada Day", "Don't Step on a Bee Day"],
  "7-11": ["Cheer up the Lonely Day", "World Population Day", "National Blueberry Muffin Day", "All American Pet Photo Day"],
  "7-12": ["Different Colored Eyes Day", "Pecan Pie Day", "Simplicity Day", "Eat Your Jell-O Day"],
  "7-13": ["Barbershop Music Appreciation Day", "Fool's Paradise Day", "National French Fries Day", "Embrace Your Geekness Day"],
  "7-14": ["Pandemonium Day", "Bastille Day", "National Grand Marnier Day", "Shark Awareness Day"],
  "7-15": ["Cow Appreciation Day", "Be a Dork Day", "National Tapioca Pudding Day", "Gummi Worm Day"],
  "7-16": ["Fresh Spinach Day", "Global Hug Your Kids Day", "National Corn Fritters Day", "World Snake Day"],
  "7-17": ["Peach Ice Cream Day", "Yellow Pig Day", "World Emoji Day", "National Tattoo Day"],
  "7-18": ["National Caviar Day", "Perfect Family Day", "Nelson Mandela International Day"],
  "7-19": ["Flitch Day", "Stick Out Your Tongue Day", "National Daiquiri Day", "National Raspberry Cake Day"],
  "7-20": ["Moon Day", "Ugly Truck Day", "National Lollipop Day", "National Ice Cream Soda Day"],
  "7-21": ["National Junk Food Day", "Take a Monkey to Lunch Day", "Legal Drinking Age Day"],
  "7-22": ["Ratcatcher's Day", "Hammock Day", "National Penuche Fudge Day", "Pi Approximation Day"],
  "7-23": ["Vanilla Ice Cream Day", "Gorgeous Grandma Day", "Hot Enough For Ya Day"],
  "7-24": ["Amelia Earhart Day", "Cousins Day", "National Tequila Day", "Tell an Old Joke Day"],
  "7-25": ["Threading the Needle Day", "Culinarians Day", "National Hot Fudge Sundae Day", "Merry-Go-Round Day"],
  "7-26": ["All or Nothing Day", "Aunt and Uncle Day", "National Coffee Milkshake Day", "Bagelfest Day"],
  "7-27": ["Take Your Pants for a Walk Day", "National Scotch Day", "Walk on Stilts Day", "Barbie in a Blender Day"],
  "7-28": ["National Milk Chocolate Day", "Buffalo Soldiers Day", "World Hepatitis Day"],
  "7-29": ["National Lasagna Day", "Rain Day", "National Chicken Wing Day", "International Tiger Day"],
  "7-30": ["Father-in-Law Day", "National Cheesecake Day", "International Day of Friendship", "Paperback Book Day"],
  "7-31": ["Mutt's Day", "Jump for Jelly Beans Day", "Uncommon Instrument Awareness Day", "National Avocado Day"],

  "8-1": ["Respect for Parents Day", "Girlfriend's Day", "National Raspberry Cream Pie Day", "World Wide Web Day"],
  "8-2": ["National Ice Cream Sandwich Day", "National Coloring Book Day", "Dinosaurs Day"],
  "8-3": ["Grab Some Nuts Day", "National Watermelon Day", "National Georgia Day"],
  "8-4": ["Twins Day Festival", "U.S. Coast Guard Day", "National Chocolate Chip Cookie Day", "Single Working Women's Day"],
  "8-5": ["National Underwear Day", "Work Like a Dog Day", "National Oyster Day", "Beach Day"],
  "8-6": ["Fresh Breath Day", "Wiggle Your Toes Day", "National Root Beer Float Day"],
  "8-7": ["Particularly Preposterous Packaging Day", "National Raspberries N' Cream Day", "Sea Serpent Day", "Lighthouse Day"],
  "8-8": ["Sneak Some Zucchini Onto Your Neighbor's Porch Day", "Happiness Happens Day", "International Cat Day", "National Frozen Custard Day"],
  "8-9": ["Book Lovers Day", "National Rice Pudding Day", "Veep Day"],
  "8-10": ["Lazy Day", "National S'mores Day", "World Lion Day"],
  "8-11": ["Presidential Joke Day", "Play in the Sand Day", "National Raspberry Bombe Day", "Son and Daughter Day"],
  "8-12": ["Middle Child's Day", "Vinyl Record Day", "World Elephant Day", "National Julienne Fries Day"],
  "8-13": ["Left Hander's Day", "Blame Someone Else Day", "National Filet Mignon Day", "Prosecco Day"],
  "8-14": ["Creamsicle Day", "National Navajo Code Talkers Day", "Color Book Day"],
  "8-15": ["Relaxation Day", "National Failures Day", "National Lemon Meringue Pie Day", "Best Friends Day"],
  "8-16": ["Bratwurst Festival", "National Rum Day", "National Tell a Joke Day", "Roller Coaster Day"],
  "8-17": ["National Thrift Shop Day", "Meaning of \u201cIs\u201d Day", "I Love My Feet Day"],
  "8-18": ["Bad Poetry Day", "Mail Order Catalog Day", "National Ice Cream Pie Day", "Serendipity Day"],
  "8-19": ["Aviation Day", "Potato Day", "National Soft Ice Cream Day", "World Photography Day"],
  "8-20": ["National Radio Day", "Chocolate Pecan Pie Day", "World Mosquito Day"],
  "8-21": ["Senior Citizen's Day", "Spumoni Day", "Poet's Day"],
  "8-22": ["Be an Angel Day", "National Tooth Fairy Day", "National Pecan Torte Day"],
  "8-23": ["Ride the Wind Day", "Valentino Day", "National Sponge Cake Day", "Cuban Sandwich Day"],
  "8-24": ["National Waffle Day", "Vesuvius Day", "Knife Day", "Pluto Demoted Day"],
  "8-25": ["Kiss and Make Up Day", "National Banana Split Day", "National Whiskey Sour Day", "Second-Hand Wardrobe Day"],
  "8-26": ["National Dog Day", "Women's Equality Day", "National Cherry Popsicle Day", "Toilet Paper Day"],
  "8-27": ["Just Because Day", "Global Forgiveness Day", "National Pots De Creme Day", "The Duchess Who Wasn't Day"],
  "8-28": ["Race Your Mouse Around the Icons Day", "National Cherry Turnover Day", "Radio Commercials Day"],
  "8-29": ["More Herbs, Less Salt Day", "According to Hoyle Day", "National Chop Suey Day", "Individual Rights Day"],
  "8-30": ["Frankenstein Day", "Toasted Marshmallow Day", "National Beach Day", "Slinky Day"],
  "8-31": ["National Trail Mix Day", "Eat Outside Day", "Love Litigating Lawyers Day"],

  "9-1": ["Emma M. Nutt Day", "National Cherry Popover Day", "Chicken Boy's Day"],
  "9-2": ["National Beheading Day", "V-J Day", "Bison-ten Yell Day", "World Coconut Day"],
  "9-3": ["Skyscraper Day", "National Welsh Rarebit Day", "Bowling League Day"],
  "9-4": ["Newspaper Carrier Day", "National Macadamia Nut Day", "Eat an Extra Dessert Day", "National Wildlife Day"],
  "9-5": ["Be Late for Something Day", "National Cheese Pizza Day", "International Day of Charity"],
  "9-6": ["Fight Procrastination Day", "Read a Book Day", "National Coffee Ice Cream Day"],
  "9-7": ["Neither Rain nor Snow Day", "Salami Day", "National Beer Lover's Day"],
  "9-8": ["Pardon Day", "National Date Nut Bread Day", "International Literacy Day", "Star Trek Day"],
  "9-9": ["Teddy Bear Day", "National Wiener Schnitzel Day", "Wonderful Weirdos Day"],
  "9-10": ["Sew Be It Day", "Swap Ideas Day", "National TV Dinner Day", "National Ants on a Log Day"],
  "9-11": ["Patriot Day", "No News is Good News Day", "Make Your Bed Day", "National Hot Cross Bun Day"],
  "9-12": ["National Chocolate Milkshake Day", "Video Games Day", "National Day of Encouragement"],
  "9-13": ["Defy Superstition Day", "Fortune Cookie Day", "National Peanut Day", "Positive Thinking Day"],
  "9-14": ["National Cream-Filled Donut Day", "Eat a Hoagie Day", "National Coloring Day"],
  "9-15": ["Make a Hat Day", "Felt Hat Day", "National Linguine Day", "Greenpeace Day"],
  "9-16": ["American Legion Day", "Collect Rocks Day", "National Guacamole Day", "Play-Doh Day"],
  "9-17": ["Constitution Day", "National Apple Dumpling Day", "Citizenship Day", "International Country Music Day"],
  "9-18": ["National Cheeseburger Day", "Rice Krispie Treat Day", "World Water Monitoring Day"],
  "9-19": ["International Talk Like a Pirate Day", "National Butterscotch Pudding Day", "National Gymnastics Day"],
  "9-20": ["National Punch Day", "String Cheese Day", "National Fried Rice Day"],
  "9-21": ["World Gratitude Day", "International Day of Peace", "Miniature Golf Day", "National Pecan Cookie Day"],
  "9-22": ["Business Women's Day", "Dear Diary Day", "Hobbit Day", "Elephant Appreciation Day"],
  "9-23": ["Checkers Day", "Dogs in Politics Day", "National White Chocolate Day", "Restless Legs Awareness Day"],
  "9-24": ["National Cherries Jubilee Day", "Punctuation Day", "Bluebird of Happiness Day"],
  "9-25": ["National Comic Book Day", "National Lobster Day", "One-Hit Wonder Day", "Math Storytelling Day"],
  "9-26": ["Johnny Appleseed Day", "National Pancake Day", "National Situational Awareness Day"],
  "9-27": ["Crush a Can Day", "National Chocolate Milk Day", "Ancestor Appreciation Day", "World Tourism Day"],
  "9-28": ["Ask a Stupid Question Day", "National Drink Beer Day", "National Strawberry Cream Pie Day", "Good Neighbor Day"],
  "9-29": ["Confucius Day", "National Coffee Day", "World Heart Day", "National Biscotti Day"],
  "9-30": ["National Mud Pack Day", "National Hot Mulled Cider Day", "International Podcast Day", "Blasphemy Day"],

  "10-1": ["World Vegetarian Day", "International Coffee Day", "National Homemade Cookies Day", "Fire Pup Day"],
  "10-2": ["Name Your Car Day", "World Farm Animals Day", "National Fried Scallops Day", "Phileas Fogg Wager Day"],
  "10-3": ["Techies Day", "Virus Appreciation Day", "National Caramel Custard Day", "Mean Girls Day"],
  "10-4": ["Improve Your Office Day", "Ten-Four Day", "National Taco Day", "National Golf Lover's Day"],
  "10-5": ["World Teacher's Day", "Do Something Nice Day", "National Apple Betty Day", "Get Funky Day"],
  "10-6": ["Come and Take it Day", "German-American Day", "National Noodle Day", "Mad Hatter Day"],
  "10-7": ["Bald and Free Day", "National Frappe Day", "Bathtub Day"],
  "10-8": ["American Touch Tag Day", "National Fluffernutter Day", "Emergency Nurses Day"],
  "10-9": ["Curious Events Day", "Fire Prevention Day", "Moldy Cheese Day", "Leif Erikson Day"],
  "10-10": ["National Angel Food Cake Day", "Cake Decorating Day", "World Porridge Day", "Handbag Day"],
  "10-11": ["It's My Party Day", "Southern Food Heritage Day", "National Sausage Pizza Day"],
  "10-12": ["International Moment of Frustration Scream Day", "Cookbook Launch Day", "National Gumbo Day", "Old Farmer's Day"],
  "10-13": ["International Skeptics Day", "National Yorkshire Pudding Day", "Train Your Brain Day"],
  "10-14": ["Be Bald and Be Free Day", "National Dessert Day", "World Standards Day"],
  "10-15": ["White Cane Safety Day", "National Grouch Day", "National Chicken Cacciatore Day", "Global Handwashing Day"],
  "10-16": ["Dictionary Day", "National Liqueur Day", "World Food Day", "Steve Jobs Day"],
  "10-17": ["Wear Something Gaudy Day", "National Pasta Day", "Mulligan Day"],
  "10-18": ["No Beard Day", "National Chocolate Cupcake Day", "Alaska Day"],
  "10-19": ["Evaluate Your Life Day", "National Seafood Bisque Day", "New Friends Day"],
  "10-20": ["Brandied Fruit Day", "National Youth Confidence Day", "International Sloth Day"],
  "10-21": ["Babbling Day", "Count Your Buttons Day", "National Pumpkin Cheesecake Day", "Reptile Awareness Day"],
  "10-22": ["National Nut Day", "Smart is Cool Day", "National Color Day", "Caps Lock Day"],
  "10-23": ["National Mole Day", "TV Talk Show Host Day", "iPod Day", "Boston Cream Pie Day"],
  "10-24": ["National Bologna Day", "United Nations Day", "National Food Day"],
  "10-25": ["Punk for a Day Day", "Sourest Day", "World Pasta Day", "National Greasy Foods Day"],
  "10-26": ["National Mincemeat Day", "National Pumpkin Day", "Howl at the Moon Day"],
  "10-27": ["American Beer Day", "Navy Day", "Cranky Co-Workers Day", "Boxer Shorts Day"],
  "10-28": ["Plush Animal Lover's Day", "National Chocolate Day", "Wild Foods Day"],
  "10-29": ["Hermit Day", "National Cat Day", "National Oatmeal Day", "Internet Day"],
  "10-30": ["National Candy Corn Day", "Mischief Night", "Create a Great Funeral Day", "Checklist Day"],
  "10-31": ["Halloween", "National Magic Day", "Increase Your Psychic Powers Day", "Carve a Pumpkin Day"],

  "11-1": ["All Saints Day", "Cook Something Bold Day", "Day of the Dead", "National Vinegar Day", "Extra Mile Day"],
  "11-2": ["All Souls Day", "Deviled Egg Day", "Look for Circles Day", "Cookie Monster Day"],
  "11-3": ["Cliche Day", "Housewife's Day", "Sandwich Day", "National Jellyfish Day"],
  "11-4": ["King Tut Day", "Waiting for the Barbarians Day", "National Candy Day", "Use Your Common Sense Day"],
  "11-5": ["Gunpowder Day", "Job Action Day", "National Doughnut Day", "American Football Day"],
  "11-6": ["Marooned Without a Compass Day", "Saxophone Day", "National Nachos Day"],
  "11-7": ["Bittersweet Chocolate with Almonds Day", "Hug a Bear Day", "Book Lovers Day"],
  "11-8": ["Dunce Day", "National Cappuccino Day", "Abet and Aid Punsters Day"],
  "11-9": ["Chaos Never Dies Day", "Young Readers Day", "National Scrapple Day"],
  "11-10": ["Forget-Me-Not Day", "U.S. Marine Corps Day", "Area Code Day", "National Vanilla Cupcake Day"],
  "11-11": ["Veterans Day", "Origami Day", "National Sundae Day", "Singles Day"],
  "11-12": ["Chicken Soup for the Soul Day", "National Pizza with the Works Except Anchovies Day", "Happy Hour Day"],
  "11-13": ["World Kindness Day", "National Indian Pudding Day", "Caregiver Appreciation Day"],
  "11-14": ["Operating Room Nurse Day", "National Pickle Day", "Loosen Up Lighten Up Day", "World Diabetes Day"],
  "11-15": ["America Recycles Day", "Clean Out Your Refrigerator Day", "National Bundt Day", "I Love to Write Day"],
  "11-16": ["Button Day", "Have a Party With Your Bear Day", "National Fast Food Day"],
  "11-17": ["Homemade Bread Day", "Take a Hike Day", "Electronic Greeting Card Day", "World Peace Day"],
  "11-18": ["Occult Day", "Princess Day", "Mickey Mouse Birthday", "National Vichyssoise Day"],
  "11-19": ["Have a Bad Day Day", "World Toilet Day", "National Carbonated Beverage With Caffeine Day"],
  "11-20": ["Absurdity Day", "Beautiful Day", "National Peanut Butter Fudge Day", "Name Your PC Day"],
  "11-21": ["False Confession Day", "World Hello Day", "National Gingerbread Day", "Red Mitten Day"],
  "11-22": ["Go For a Ride Day", "Start Your Own Country Day", "National Cashew Day"],
  "11-23": ["Eat a Cranberry Day", "National Espresso Day", "Fibonacci Day", "Doctor Who Day"],
  "11-24": ["All Our Uncles are Monkeys Day", "National Sardines Day", "Celebrate Your Unique Talent Day"],
  "11-25": ["Shopping Reminder Day", "National Parfait Day", "Blase Day"],
  "11-26": ["National Cake Day", "Good Grief Day", "Shopping Reminder Day"],
  "11-27": ["Pins and Needles Day", "National Bavarian Cream Pie Day", "Turtle Adoption Day"],
  "11-28": ["Make Your Own Head Day", "French Toast Day", "Red Planet Day"],
  "11-29": ["Square Dance Day", "Chocolates Day", "Throw Out Your Leftovers Day"],
  "11-30": ["Stay At Home Because You Are Well Day", "National Mousse Day", "Computer Security Day", "Mason Jar Day"],

  "12-1": ["Eat a Red Apple Day", "Bifocals at the Monitor Liberation Day", "World AIDS Day", "Day With(out) Art Day"],
  "12-2": ["National Fritters Day", "Special Education Day", "International Day for the Abolition of Slavery"],
  "12-3": ["Make a Gift Day", "National Roof Over Your Head Day", "National Apple Pie Day"],
  "12-4": ["Wear Brown Shoes Day", "Santa's List Day", "National Cookie Day", "National Sock Day"],
  "12-5": ["Bathtub Party Day", "International Ninja Day", "Repeal Day", "National Comfort Food Day"],
  "12-6": ["Mitten Tree Day", "Microwave Oven Day", "National Gazpacho Day", "St. Nicholas Day"],
  "12-7": ["Pearl Harbor Remembrance Day", "International Civil Aviation Day", "National Cotton Candy Day"],
  "12-8": ["Take it in the Ear Day", "National Brownie Day", "Pretend to Be a Time Traveler Day"],
  "12-9": ["Christmas Card Day", "National Pastry Day", "Weary Willie Day"],
  "12-10": ["Festival for the Souls of Dead Whales", "Human Rights Day", "National Lager Day", "Dewey Decimal System Day"],
  "12-11": ["National Noodle Ring Day", "App Day", "International Mountain Day"],
  "12-12": ["Poinsettia Day", "Gingerbread House Day", "National Ambrosia Day"],
  "12-13": ["Ice Cream Day", "National Cocoa Day", "Violin Day", "National Day of the Horse"],
  "12-14": ["Bouillabaisse Day", "Roast Chestnuts Day", "Monkey Day"],
  "12-15": ["Bill of Rights Day", "Cat Herders Day", "National Cupcake Day", "Wear Your Pearls Day"],
  "12-16": ["Barbie and Barney Backlash Day", "National Chocolate Covered Anything Day", "Stupid Toy Day"],
  "12-17": ["National Maple Syrup Day", "Wright Brothers Day", "Underdog Day"],
  "12-18": ["Bake Cookies Day", "National Roast Suckling Pig Day", "Answer the Telephone Like Buddy the Elf Day"],
  "12-19": ["Look for an Evergreen Day", "Oatmeal Muffin Day", "National Hard Candy Day"],
  "12-20": ["Games Day", "Go Caroling Day", "National Sangria Day", "Mudd Day"],
  "12-21": ["Look on the Bright Side Day", "Humbug Day", "Crossword Puzzle Day", "National French Fried Shrimp Day"],
  "12-22": ["Date Nut Bread Day", "National Cookie Exchange Day", "Forefathers Day"],
  "12-23": ["Festivus", "Roots Day", "Pfeffernusse Day"],
  "12-24": ["Christmas Eve", "National Egg Nog Day", "Last-Minute Shopper's Day"],
  "12-25": ["Christmas Day", "National Pumpkin Pie Day", "A'Phabet Day / No \u201cL\u201d Day"],
  "12-26": ["Boxing Day", "National Candy Cane Day", "National Thank You Note Day", "First Day of Kwanzaa"],
  "12-27": ["Make Cut Out Snowflakes Day", "National Fruitcake Day", "Visit the Zoo Day"],
  "12-28": ["Card Playing Day", "National Chocolate Candy Day", "Pledge of Allegiance Day"],
  "12-29": ["Pepper Pot Day", "Tick Tock Day", "Still Need to Do Day"],
  "12-30": ["Bacon Day", "Falling Needles Family Fest Day", "National Bicarbonate of Soda Day"],
  "12-31": ["New Year's Eve", "Make Up Your Mind Day", "Universal Hour of Peace", "National Champagne Day"],
};

/* Month-long observances */
export const MONTHLY = {
  1: ["National Soup Month", "National Hobby Month", "National Oatmeal Month", "National Hot Tea Month", "National Blood Donor Month", "Get Organized Month", "National Mentoring Month"],
  2: ["Black History Month", "National Cherry Month", "National Bird Feeding Month", "Great American Pies Month", "National Snack Food Month", "Library Lovers Month", "National Grapefruit Month"],
  3: ["National Peanut Month", "Women's History Month", "National Craft Month", "National Celery Month", "National Frozen Food Month", "National Nutrition Month", "National Umbrella Month"],
  4: ["National Humor Month", "National Poetry Month", "National Garden Month", "Stress Awareness Month", "National Grilled Cheese Month", "Jazz Appreciation Month", "National Soft Pretzel Month"],
  5: ["National Barbecue Month", "National Hamburger Month", "National Salad Month", "National Bike Month", "National Photo Month", "National Egg Month", "Older Americans Month", "National Strawberry Month"],
  6: ["National Candy Month", "National Dairy Month", "National Iced Tea Month", "Great Outdoors Month", "National Rose Month", "National Camping Month", "National Soul Food Month"],
  7: ["National Anti-Boredom Month", "National Baked Bean Month", "National Hot Dog Month", "National Ice Cream Month", "National Picnic Month", "National Blueberry Month", "National Grilling Month"],
  8: ["National Catfish Month", "National Golf Month", "Family Fun Month", "National Panini Month", "National Peach Month", "Romance Awareness Month", "Happiness Happens Month"],
  9: ["National Chicken Month", "National Honey Month", "National Piano Month", "Classical Music Month", "Better Breakfast Month", "National Courtesy Month"],
  10: ["National Pizza Month", "National Popcorn Poppin' Month", "National Caramel Month", "National Dessert Month", "Adopt a Shelter Dog Month", "National Book Month", "National Sarcastic Month"],
  11: ["National Peanut Butter Lovers Month", "National Georgia Pecan Month", "National Novel Writing Month", "National Gratitude Month", "Aviation History Month", "National Pomegranate Month"],
  12: ["National Egg Nog Month", "Bingo's Birthday Month", "National Fruit Cake Month", "Write a Business Plan Month", "Universal Human Rights Month"],
};

/* Multi-day observances.
   range   -> fixed dates: { m, from, to }
   week    -> nth full week of the month starting on a weekday: { m, nth, dow }
   weekOf  -> the week containing a fixed date: { m, day, dow }  (dow = week start)
   lastWeek-> last full week of the month: { m, dow }            */
export const SPANS = [
  { name: "Universal Letter Writing Week", type: "range", m: 1, from: 8, to: 14 },
  { name: "National Pizza Week", type: "week", m: 1, nth: 2, dow: 0 },
  { name: "National Hunt for Happiness Week", type: "week", m: 1, nth: 3, dow: 0 },
  { name: "Healthy Weight Week", type: "week", m: 1, nth: 3, dow: 0 },

  { name: "National School Counseling Week", type: "week", m: 2, nth: 1, dow: 0 },
  { name: "International Flirting Week", type: "week", m: 2, nth: 2, dow: 0 },
  { name: "Random Acts of Kindness Week", type: "range", m: 2, from: 14, to: 20 },
  { name: "National Pancake Week", type: "lastWeek", m: 2, dow: 0 },

  { name: "Newspaper in Education Week", type: "week", m: 3, nth: 1, dow: 0 },
  { name: "Girl Scout Week", type: "range", m: 3, from: 6, to: 12 },
  { name: "National Sleep Awareness Week", type: "week", m: 3, nth: 2, dow: 0 },
  { name: "National Bubble Week", type: "week", m: 3, nth: 3, dow: 0 },

  { name: "Golden Rule Week", type: "range", m: 4, from: 1, to: 7 },
  { name: "National Library Week", type: "week", m: 4, nth: 2, dow: 0 },
  { name: "National Volunteer Week", type: "week", m: 4, nth: 3, dow: 0 },
  { name: "National Park Week", type: "week", m: 4, nth: 3, dow: 6 },

  { name: "Teacher Appreciation Week", type: "week", m: 5, nth: 1, dow: 0 },
  { name: "National Pet Week", type: "week", m: 5, nth: 1, dow: 0 },
  { name: "National Nurses Week", type: "range", m: 5, from: 6, to: 12 },
  { name: "National Police Week", type: "weekOf", m: 5, day: 15, dow: 0 },
  { name: "National Bike to Work Week", type: "week", m: 5, nth: 3, dow: 1 },

  { name: "National Fishing and Boating Week", type: "week", m: 6, nth: 1, dow: 6 },
  { name: "National Flag Week", type: "weekOf", m: 6, day: 14, dow: 0 },
  { name: "National Camping Week", type: "week", m: 6, nth: 2, dow: 0 },

  { name: "Nude Recreation Week", type: "week", m: 7, nth: 2, dow: 1 },
  { name: "National Farriers Week", type: "week", m: 7, nth: 2, dow: 0 },
  { name: "Everybody Deserves a Massage Week", type: "range", m: 7, from: 14, to: 20 },

  { name: "International Clown Week", type: "range", m: 8, from: 1, to: 7 },
  { name: "National Farmers Market Week", type: "week", m: 8, nth: 1, dow: 0 },
  { name: "Elvis Week", type: "range", m: 8, from: 9, to: 16 },
  { name: "National Aviation Week", type: "weekOf", m: 8, day: 19, dow: 0 },

  { name: "National Waffle Week", type: "week", m: 9, nth: 1, dow: 0 },
  { name: "National Truck Driver Appreciation Week", type: "week", m: 9, nth: 2, dow: 0 },
  { name: "National Farm Animals Awareness Week", type: "week", m: 9, nth: 3, dow: 0 },
  { name: "Deaf Awareness Week", type: "lastWeek", m: 9, dow: 0 },

  { name: "National Newspaper Week", type: "week", m: 10, nth: 1, dow: 0 },
  { name: "Fire Prevention Week", type: "weekOf", m: 10, day: 9, dow: 0 },
  { name: "Earth Science Week", type: "week", m: 10, nth: 2, dow: 0 },
  { name: "National Chemistry Week", type: "week", m: 10, nth: 3, dow: 0 },

  { name: "National Fig Week", type: "range", m: 11, from: 1, to: 7 },
  { name: "World Kindness Week", type: "week", m: 11, nth: 2, dow: 0 },
  { name: "National Game & Puzzle Week", type: "lastWeek", m: 11, dow: 0 },

  { name: "Cookie Cutter Week", type: "range", m: 12, from: 1, to: 7 },
  { name: "Recipe Greetings for the Holidays Week", type: "range", m: 12, from: 1, to: 7 },
  { name: "Christmas Bird Count Week", type: "range", m: 12, from: 14, to: 21 },
  { name: "Kwanzaa", type: "range", m: 12, from: 26, to: 31 },
];

/* Holidays that move around the calendar */
export const FLOATING = [
  { name: "Martin Luther King Jr. Day", type: "nth", m: 1, nth: 3, dow: 1 },
  { name: "Bubble Wrap Appreciation Day", type: "last", m: 1, dow: 1 },
  { name: "Super Bowl Sunday", type: "nth", m: 2, nth: 2, dow: 0 },
  { name: "Presidents' Day", type: "nth", m: 2, nth: 3, dow: 1 },
  { name: "Daylight Saving Time Begins", type: "nth", m: 3, nth: 2, dow: 0 },
  { name: "Free Comic Book Day", type: "nth", m: 5, nth: 1, dow: 6 },
  { name: "Mother's Day", type: "nth", m: 5, nth: 2, dow: 0 },
  { name: "Armed Forces Day", type: "nth", m: 5, nth: 3, dow: 6 },
  { name: "Memorial Day", type: "last", m: 5, dow: 1 },
  { name: "National Doughnut Day", type: "nth", m: 6, nth: 1, dow: 5 },
  { name: "Father's Day", type: "nth", m: 6, nth: 3, dow: 0 },
  { name: "Take Your Dog to Work Day", type: "offset", from: { m: 6, nth: 3, dow: 0 }, days: 5 },
  { name: "Labor Day", type: "nth", m: 9, nth: 1, dow: 1 },
  { name: "National Grandparents Day", type: "offset", from: { m: 9, nth: 1, dow: 1 }, days: 6 },
  { name: "Columbus Day", type: "nth", m: 10, nth: 2, dow: 1 },
  { name: "Indigenous Peoples' Day", type: "nth", m: 10, nth: 2, dow: 1 },
  { name: "Boss's Day Observed", type: "nth", m: 10, nth: 3, dow: 5 },
  { name: "Sweetest Day", type: "nth", m: 10, nth: 3, dow: 6 },
  { name: "Daylight Saving Time Ends", type: "nth", m: 11, nth: 1, dow: 0 },
  { name: "Election Day", type: "offset", from: { m: 11, nth: 1, dow: 1 }, days: 1 },
  { name: "Great American Smokeout", type: "nth", m: 11, nth: 3, dow: 4 },
  { name: "Thanksgiving Day", type: "nth", m: 11, nth: 4, dow: 4 },
  { name: "Black Friday", type: "offset", from: { m: 11, nth: 4, dow: 4 }, days: 1 },
  { name: "Small Business Saturday", type: "offset", from: { m: 11, nth: 4, dow: 4 }, days: 2 },
  { name: "Cyber Monday", type: "offset", from: { m: 11, nth: 4, dow: 4 }, days: 4 },
];

/* Easter-anchored holidays, offset in days from Easter Sunday */
export const EASTER_BASED = [
  { name: "Mardi Gras", offset: -47 },
  { name: "Ash Wednesday", offset: -46 },
  { name: "Palm Sunday", offset: -7 },
  { name: "Good Friday", offset: -2 },
  { name: "Easter Sunday", offset: 0 },
  { name: "Easter Monday", offset: 1 },
];
